---
title: "Reweighting"
author: "Eirik Sjåvik"
date: "2023-04-04"
output: html_document
---

# First Produce re-weighted data: 
```{r}
# dir  ='/mn/kadingir/datascience_000000/eirikhsj/'
# file_path = paste0(dir,'sfe_nordic_temperature/')
dir = '/nr/samba/user/esjavik/DemandModels/'
file_path = '/nr/samba/user/esjavik//bigdisk3/pro/sfe_daily_nordic_temperature/'

NWP_quant_rew25_1993_2023_1 = get_all_NWP_quantiles(path = file_path,
                                                    pattern = 'sfe_nordic_temperature_',
                                                    start_month  = '01', start_year = 1993, forc_months = 362,
                                                    PC_ERA_path = paste0(dir,"PC_ERA_79_92.Rda"),
                                                    pc_comp = 1,
                                                    reweight = TRUE, rew_int =c(15, 1), rew_type = 'get_beta_weights') # 1 day, last day 15th

NWP_quant_rew25_1993_2023_2 = get_all_NWP_quantiles(path = "/mn/kadingir/datascience_000000/eirikhsj/sfe_nordic_temperature/",
                                                    pattern = 'sfe_nordic_temperature_',
                                                    start_month  = '01', start_year = 1993, forc_months = 362,
                                                    PC_ERA_path = "/mn/kadingir/datascience_000000/eirikhsj/PC_ERA_79_92.Rda",
                                                    pc_comp = 1,
                                                    reweight = TRUE, rew_int =c(15, 2))  # 2 days

NWP_quant_rew25_1993_2023_3 = get_all_NWP_quantiles(path = "/mn/kadingir/datascience_000000/eirikhsj/sfe_nordic_temperature/",
                                                    pattern = 'sfe_nordic_temperature_',
                                                    start_month  = '01', start_year = 1993, forc_months = 362,
                                                    PC_ERA_path = "/mn/kadingir/datascience_000000/eirikhsj/PC_ERA_79_92.Rda",
                                                    pc_comp = 1,
                                                    reweight = TRUE, rew_int =c(15, 3)) # 3 days
```



# Run models: QR-NWP1: y = B NWP1
```{r}
#For 1 days of re-weighting
for (k in 1:25){
    ERA_NWP = get_ERA_NWP(ERA_path = "/mn/kadingir/datascience_000000/eirikhsj/PC_ERA_79_92.Rda",
                          NWP_path ="/mn/kadingir/datascience_000000/eirikhsj/NWP_quant_rew25_1993_2023_1.Rda",
                          quant = "90", reweight = TRUE, tuning_k = k)

    ERA_NWP[, season:= ifelse(month(date) %in% c(12,1,2), 1,
                              ifelse(month(date) %in% c(3,4,5), 2,
                                     ifelse(month(date) %in% c(6,7,8), 3, 4)))]
    print(paste0('Got data for tuning param K =  ',k))

    mod_k   = rolling_mod_NWP_interval('2007-01-01', '2023-01-31', 0.9, ERA_NWP, model = 'qreg', window = 125, cores = 48, formula  = 'PC1 ~ NWP1_re90', interval_k = 125*4)
    
    assign(paste0('mod_', k), mod_k)
    save(list =paste0('mod_', k), file = paste0('~/rew_k_',k,'_1.Rda'))
}

#For 2 days of re-weighting
for (k in 1:25){
    ERA_NWP = get_ERA_NWP(ERA_path = "/mn/kadingir/datascience_000000/eirikhsj/PC_ERA_79_92.Rda",
                          NWP_path ="/mn/kadingir/datascience_000000/eirikhsj/NWP_quant_rew25_1993_2023_2.Rda",
                          quant = "90", reweight = TRUE, tuning_k = k)

    ERA_NWP[, season:= ifelse(month(date) %in% c(12,1,2), 1,
                              ifelse(month(date) %in% c(3,4,5), 2,
                                     ifelse(month(date) %in% c(6,7,8), 3, 4)))]
    print(paste0('Got data for tuning param K =  ',k))

    mod_k   = rolling_mod_NWP_interval('2007-01-01', '2023-01-31', 0.9, ERA_NWP, model = 'qreg', window = 125, cores = 48, formula  = 'PC1 ~ NWP1_re90', interval_k = 125*4)
    
    assign(paste0('mod_', k), mod_k)
    save(list =paste0('mod_', k), file = paste0('~/rew_k_',k,'_2.Rda'))
}

#For 3 days of re-weighting
for (k in 1:25){
    ERA_NWP = get_ERA_NWP(ERA_path = "/mn/kadingir/datascience_000000/eirikhsj/PC_ERA_79_92.Rda",
                          NWP_path ="/mn/kadingir/datascience_000000/eirikhsj/NWP_quant_rew25_1993_2023_3.Rda",
                          quant = "90", reweight = TRUE, tuning_k = k)

    ERA_NWP[, season:= ifelse(month(date) %in% c(12,1,2), 1,
                              ifelse(month(date) %in% c(3,4,5), 2,
                                     ifelse(month(date) %in% c(6,7,8), 3, 4)))]
    print(paste0('Got data for tuning param K =  ',k))

    mod_k   = rolling_mod_NWP_interval('2007-01-01', '2023-01-31', 0.9, ERA_NWP, model = 'qreg', window = 125, cores = 48, formula  = 'PC1 ~ NWP1_re90', interval_k = 125*4)
    
    assign(paste0('mod_', k), mod_k)
    save(list =paste0('mod_', k), file = paste0('~/rew_k_',k,'_3.Rda'))
}

```


# Run models: QR-combined:  y = B interactions
```{r}
#For 1 days of re-weighting
for (k in 1:25){
    ERA_NWP = get_ERA_NWP(ERA_path = "/mn/kadingir/datascience_000000/eirikhsj/PC_ERA_79_92.Rda",
                          NWP_path ="/mn/kadingir/datascience_000000/eirikhsj/NWP_quant_rew25_1993_2023_1.Rda",
                          quant = "90", reweight = TRUE, tuning_k = k)

    ERA_NWP[, season:= ifelse(month(date) %in% c(12,1,2), 1,
                              ifelse(month(date) %in% c(3,4,5), 2,
                                     ifelse(month(date) %in% c(6,7,8), 3, 4)))]
    print(paste0('Got data for tuning param K =  ',k))

    mod_int1_k   = 
    rolling_mod_NWP_interval('2007-01-01', '2023-01-31', 0.9, ERA_NWP, model = 'qreg', window = 125, cores = 48, formula  = 'PC1 ~ 1 + as.factor(hour)*as.factor(season) + cos(2*pi * week/52) + sin(2*pi * week/52) + 
                                    cos(2*pi * month/12) + sin(2*pi * month/12)  + year+ NWP1_re90 + NWP2_re90 ', interval_k = 125*4)
    
    assign(paste0('mod_int1_', k), mod_int1_k)
    save(list =paste0('mod_int1_', k), file = paste0('~/rew_k_',k,'_int1.Rda'))
}

#For 2 days of re-weighting
for (k in 1:25){
    ERA_NWP = get_ERA_NWP(ERA_path = "/mn/kadingir/datascience_000000/eirikhsj/PC_ERA_79_92.Rda",
                          NWP_path ="/mn/kadingir/datascience_000000/eirikhsj/NWP_quant_rew25_1993_2023_2.Rda",
                          quant = "90", reweight = TRUE, tuning_k = k)

    ERA_NWP[, season:= ifelse(month(date) %in% c(12,1,2), 1,
                              ifelse(month(date) %in% c(3,4,5), 2,
                                     ifelse(month(date) %in% c(6,7,8), 3, 4)))]
    print(paste0('Got data for tuning param K =  ',k))

    mod_int2_k   = 
    rolling_mod_NWP_interval('2007-01-01', '2023-01-31', 0.9, ERA_NWP, model = 'qreg', window = 125, cores = 48, formula  = 'PC1 ~ 1 + as.factor(hour)*as.factor(season) + cos(2*pi * week/52) + sin(2*pi * week/52) + 
                                    cos(2*pi * month/12) + sin(2*pi * month/12)  + year+ NWP1_re90 + NWP2_re90 ', interval_k = 125*4)
    
    assign(paste0('mod_int2_', k), mod_int2_k)
    save(list =paste0('mod_int2_', k), file = paste0('~/rew_k_',k,'_int2.Rda'))
}

#For 3 days of re-weighting
for (k in 1:25){
    ERA_NWP = get_ERA_NWP(ERA_path = "/mn/kadingir/datascience_000000/eirikhsj/PC_ERA_79_92.Rda",
                          NWP_path ="/mn/kadingir/datascience_000000/eirikhsj/NWP_quant_rew25_1993_2023_3.Rda",
                          quant = "90", reweight = TRUE, tuning_k = k)

    ERA_NWP[, season:= ifelse(month(date) %in% c(12,1,2), 1,
                              ifelse(month(date) %in% c(3,4,5), 2,
                                     ifelse(month(date) %in% c(6,7,8), 3, 4)))]
    print(paste0('Got data for tuning param K =  ',k))

    mod_int3_k   = 
    rolling_mod_NWP_interval('2007-01-01', '2023-01-31', 0.9, ERA_NWP, model = 'qreg', window = 125, cores = 48, formula  = 'PC1 ~ 1 + as.factor(hour)*as.factor(season) + cos(2*pi * week/52) + sin(2*pi * week/52) + 
                                    cos(2*pi * month/12) + sin(2*pi * month/12)  + year+ NWP1_re90 + NWP2_re90 ', interval_k = 125*4)
    
    assign(paste0('mod_int3_', k), mod_int3_k)
    save(list =paste0('mod_int3_', k), file = paste0('~/rew_k_',k,'_int3.Rda'))
}

```

# Run models: NWP-RQE:  y = NWP_re
```{r}
#For 1 days of re-weighting
ERA_NWP = get_ERA_NWP(ERA_path = "/mn/kadingir/datascience_000000/eirikhsj/PC_ERA_79_92.Rda",
                          NWP_path ="/mn/kadingir/datascience_000000/eirikhsj/NWP_quant_rew25_1993_2023_1.Rda",
                          quant = "90", reweight = TRUE, tuning_k = 1)

ERA_NWP[, season:= ifelse(month(date) %in% c(12,1,2), 1,
                          ifelse(month(date) %in% c(3,4,5), 2,
                                 ifelse(month(date) %in% c(6,7,8), 3, 4)))]
print(paste0('Got data for tuning param K =  ',1))
ERA_NWPvars = ERA_NWP[,.(date, hour, lead_time, init_date, PC1,NWP1_re90)]
ERA_NWP_RQE = ERA_NWPvars[,paste0("mean_loss_1_",1) := pinball_loss(0.9, NWP1_re90, PC1),]
    
for (k in 2:25){
    ERA_NWP = get_ERA_NWP(ERA_path = "/mn/kadingir/datascience_000000/eirikhsj/PC_ERA_79_92.Rda",
                          NWP_path ="/mn/kadingir/datascience_000000/eirikhsj/NWP_quant_rew25_1993_2023_1.Rda",
                          quant = "90", reweight = TRUE, tuning_k = k)

    ERA_NWP[, season:= ifelse(month(date) %in% c(12,1,2), 1,
                              ifelse(month(date) %in% c(3,4,5), 2,
                                     ifelse(month(date) %in% c(6,7,8), 3, 4)))]
    print(paste0('Got data for tuning param K = ',k))
    ERA_NWPvars = ERA_NWP[,.(date, hour, lead_time, init_date, PC1,NWP1_re90)]
    
    ERA_NWP_loss = ERA_NWPvars[,paste0("mean_loss_1_",k) := pinball_loss(0.9, NWP1_re90, PC1),]
    ERA_NWP_loss[,NWP1_re90 := NULL]
    ERA_NWP_RQE = merge(ERA_NWP_RQE, ERA_NWP_loss, by = c("date", "hour", "lead_time", "init_date","PC1"))
}

ERA_NWP_RQE1 = ERA_NWP_RQE


#For 2 days of re-weighting
ERA_NWP = get_ERA_NWP(ERA_path = "/mn/kadingir/datascience_000000/eirikhsj/PC_ERA_79_92.Rda",
                          NWP_path ="/mn/kadingir/datascience_000000/eirikhsj/NWP_quant_rew25_1993_2023_2.Rda",
                          quant = "90", reweight = TRUE, tuning_k = 1)

ERA_NWP[, season:= ifelse(month(date) %in% c(12,1,2), 1,
                          ifelse(month(date) %in% c(3,4,5), 2,
                                 ifelse(month(date) %in% c(6,7,8), 3, 4)))]
print(paste0('Got data for tuning param K =  ',1))
ERA_NWPvars = ERA_NWP[,.(date, hour, lead_time, init_date, PC1,NWP1_re90)]
ERA_NWP_RQE = ERA_NWPvars[,paste0("mean_loss_2_",1) := pinball_loss(0.9, NWP1_re90, PC1),]
    
for (k in 2:25){
    ERA_NWP = get_ERA_NWP(ERA_path = "/mn/kadingir/datascience_000000/eirikhsj/PC_ERA_79_92.Rda",
                          NWP_path ="/mn/kadingir/datascience_000000/eirikhsj/NWP_quant_rew25_1993_2023_2.Rda",
                          quant = "90", reweight = TRUE, tuning_k = k)

    ERA_NWP[, season:= ifelse(month(date) %in% c(12,1,2), 1,
                              ifelse(month(date) %in% c(3,4,5), 2,
                                     ifelse(month(date) %in% c(6,7,8), 3, 4)))]
    print(paste0('Got data for tuning param K = ',k))
    ERA_NWPvars = ERA_NWP[,.(date, hour, lead_time, init_date, PC1,NWP1_re90)]
    
    ERA_NWP_loss = ERA_NWPvars[,paste0("mean_loss_2_",k) := pinball_loss(0.9, NWP1_re90, PC1),]
    ERA_NWP_loss[,NWP1_re90 := NULL]
    ERA_NWP_RQE = merge(ERA_NWP_RQE, ERA_NWP_loss, by = c("date", "hour", "lead_time", "init_date","PC1"))
    
}

ERA_NWP_RQE2 = ERA_NWP_RQE


#For 3 days of re-weighting
ERA_NWP = get_ERA_NWP(ERA_path = "/mn/kadingir/datascience_000000/eirikhsj/PC_ERA_79_92.Rda",
                          NWP_path ="/mn/kadingir/datascience_000000/eirikhsj/NWP_quant_rew25_1993_2023_3.Rda",
                          quant = "90", reweight = TRUE, tuning_k = 1)

ERA_NWP[, season:= ifelse(month(date) %in% c(12,1,2), 1,
                          ifelse(month(date) %in% c(3,4,5), 2,
                                 ifelse(month(date) %in% c(6,7,8), 3, 4)))]
print(paste0('Got data for tuning param K =  ',1))
ERA_NWPvars = ERA_NWP[,.(date, hour, lead_time, init_date, PC1,NWP1_re90)]
ERA_NWP_RQE = ERA_NWPvars[,paste0("mean_loss_3_",1) := pinball_loss(0.9, NWP1_re90, PC1),]
    
for (k in 2:25){
    ERA_NWP = get_ERA_NWP(ERA_path = "/mn/kadingir/datascience_000000/eirikhsj/PC_ERA_79_92.Rda",
                          NWP_path ="/mn/kadingir/datascience_000000/eirikhsj/NWP_quant_rew25_1993_2023_3.Rda",
                          quant = "90", reweight = TRUE, tuning_k = k)

    ERA_NWP[, season:= ifelse(month(date) %in% c(12,1,2), 1,
                              ifelse(month(date) %in% c(3,4,5), 2,
                                     ifelse(month(date) %in% c(6,7,8), 3, 4)))]
    print(paste0('Got data for tuning param K = ',k))
    ERA_NWPvars = ERA_NWP[,.(date, hour, lead_time, init_date, PC1, NWP1_re90)]
    
    ERA_NWP_loss = ERA_NWPvars[,paste0("mean_loss_3_",k) := pinball_loss(0.9, NWP1_re90, PC1),]
    ERA_NWP_loss[,NWP1_re90 := NULL]
    ERA_NWP_RQE = merge(ERA_NWP_RQE, ERA_NWP_loss, by = c("date", "hour", "lead_time", "init_date","PC1"))
}

ERA_NWP_RQE3 = ERA_NWP_RQE


```

#Best RQE-models
```{r}
a = 100
b = 120
for (k in 1:25){
    col1 = paste0("mean_loss_",1,"_",k)
    col2 = paste0("mean_loss_",2,"_",k)
    col3 = paste0("mean_loss_",3,"_",k)
    
    R1 = ERA_NWP_RQE1[date>=as.Date("2007-01-01") & lead_time>a & lead_time<=b,mean(get(col1))]
    R2 = ERA_NWP_RQE2[date>=as.Date("2007-01-01") & lead_time>a & lead_time<=b,mean(get(col2))]
    R3 = ERA_NWP_RQE3[date>=as.Date("2007-01-01") & lead_time>a & lead_time<=b,mean(get(col3))]
    W1 = ERA_NWP_raw_loss[date>=as.Date("2007-01-01") & lead_time>a & lead_time<=b,mean(raw_loss_09)]
    Q1 = Interval_Mod_9_125_1$Results[date>=as.Date("2007-01-01") & lead_time>a & lead_time<=b, mean(test_loss)]
    Q_comp = Interval_Mod_9_125_hs_1_2$Results[date>=as.Date("2007-01-01") & lead_time>a & lead_time<=b, mean(test_loss)]
    C1 = Clima[date>=as.Date("2007-01-01") &lead_time >a & lead_time<=b, mean(pinball_loss(0.9, clima_pred90, PC1))]
    
    # print(
    #     c(round(k,1),
    #     1 - (R1/W1),
    #     1 - (R2/Q1),
    #     1 - (R3/Q_comp)
    # ))
    # print(
    #     c(round(k,1), 
    #     1 - (R1/C1),
    #     1 - (R2/C1),
    #     1 - (R3/C1)
    # ))
    print(c(
        round(k,1),W1,
        ERA_NWP_RQE1[date>=as.Date("2007-01-01") & lead_time>a & lead_time<=b,mean(get(col1))],
          ERA_NWP_RQE2[date>=as.Date("2007-01-01") & lead_time>a & lead_time<=b,mean(get(col2))],
          ERA_NWP_RQE3[date>=as.Date("2007-01-01") & lead_time>a & lead_time<=b,mean(get(col3))],
          Clima[date>=as.Date("2007-01-01") &lead_time >a & lead_time<=b, mean(pinball_loss(0.9, clima_pred90, PC1))]))


}
```


```{r}
pdf("/Users/Eirik/Desktop/Master2023/ExportedPlots/Reweighting.pdf", height = 5, width = 7, pointsize = 12)
p = ggplot() +
    geom_line(data = ERA_NWP_RQE1[date>=as.Date("2007-01-01") & lead_time>60 & lead_time<=120, 
                                  .(mean_test_loss = mean(mean_loss_1_5)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K5'),alpha = 1)+
    geom_line(data = ERA_NWP_RQE1[date>=as.Date("2007-01-01") & lead_time>60 & lead_time<=120, 
                                  .(mean_test_loss = mean(mean_loss_1_10)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K10'),alpha = 1)+
    geom_line(data = ERA_NWP_RQE1[date>=as.Date("2007-01-01") & lead_time>60 & lead_time<=120, 
                                  .(mean_test_loss = mean(mean_loss_1_15)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K15'),alpha = 1)+
    geom_line(data = ERA_NWP_RQE1[date>=as.Date("2007-01-01") & lead_time>60 & lead_time<=120, 
                                  .(mean_test_loss = mean(mean_loss_1_25)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K25'),alpha = 1)+
    geom_line(data = Clima[lead_time <121,
                                mean(pinball_loss(0.9, clima_pred90, PC1)), by = lead_time], aes(x = lead_time, y = V1, col = 'Climatology'),alpha = 1)+
    geom_line(data = ERA_NWP_raw_loss[lead_time <121, mean(raw_loss_09), by = lead_time], aes(x = lead_time, y = V1, col = 'NWP'),alpha = 1)+
    geom_line(data = ERA_NWP_RQE1[date>=as.Date("2007-01-01") & lead_time>60 & lead_time<=120, 
                                  .(mean_test_loss = mean(mean_loss_1_19)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K19'),alpha = 1)+
    ylim(2, 12.1)+
    scale_x_continuous(breaks=seq(0, 30, by = 5)*4,labels=c(0,5,10,15, 20,25,30))+
    labs(color = "Model:", x = "Lead Time (Days)", y = "Mean Pinball Loss",title = "Mean Pinball Loss for NWP-RQE Model by Lead Time")+
     scale_color_manual(values = c('K5'="#f2f2f2",'K10'="#f2f2f2", 'K15'="#bfbfbf",'K19'="#EF5350",'K25'='#8c8c8c', "Climatology"= 'blue', 'NWP' = 'black'),
                    labels = c(K5 = expression(paste("RQE (",gamma, "=4.6e-06)")),
                               K10 = expression(paste("RQE (",gamma, "=3.2e-05)")),
                               K15 = expression(paste("RQE (",gamma, "=2.2e-04)")),
                               K19 = expression(paste("RQE (",gamma, "=0.001)")),
                               K25 = expression(paste("RQE (",gamma, "=0.01)")),
                               Climatology = 'Climatology',
                               NWP= 'NWP-WQE')
                    )+
    geom_vline(xintercept = 15*4, linetype ='dashed', col = 'black',alpha = 0.6)+
    geom_vline(xintercept = 14*4, linetype ='dashed', col = 'black',alpha = 0.6)+
    theme_bw()+
    theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), 
          legend.position = c(0.85, 0.32), legend.key.size = unit(0.53, "cm"), legend.box.background = element_rect(color = "black", fill = NA)) 
p
dev.off()

```


```{r}
p = ggplot() +
    geom_line(data = data.table(lead_time = 1:64, skill = ERA_NWP_RQE1[lead_time>60& lead_time<=124, .(mean_test_loss = mean(mean_loss_1_17)), keyby = lead_time][,mean_test_loss]), aes(x = lead_time, y = skill, col = 'RQE1'),alpha = 1, linetype = 1)+
    
     geom_line(data = data.table(lead_time = 1:64, skill = mod_17_1$Results[lead_time>60& lead_time<=124, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = lead_time, y = skill, col = 'QR-NWP1'),alpha = 1, linetype = 1)+
    geom_line(data = data.table(lead_time = 1:64, skill = mod_int1_17$Results[lead_time>60& lead_time<=124, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = lead_time, y = skill, col = 'QR-NWP Inter'),alpha = 1, linetype = 1)
```



```{r}
pdf("/Users/Eirik/Desktop/Master2023/ExportedPlots/Skill_rew_new.pdf", height = 5, width = 7, pointsize = 12)
p = ggplot() +
    geom_line(data = data.table(lead_time = 1:80, skill = 1 - ERA_NWP_RQE1[date>=as.Date("2007-01-01") & lead_time>60& lead_time<=140, .(mean_test_loss = mean(mean_loss_1_19)), keyby = lead_time][,mean_test_loss]/Clima[lead_time>60& lead_time<=140, mean(pinball_loss(0.9, clima_pred90, PC1)), by = lead_time][,V1] ), aes(x = lead_time, y = skill, col = 'RQE'),alpha = 1, linetype = 1)+
    
     geom_line(data = data.table(lead_time = 1:80, skill = 1 - mod_19_1$Results[lead_time>60& lead_time<=140, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Clima[lead_time>60& lead_time<=140, mean(pinball_loss(0.9, clima_pred90, PC1)), by = lead_time][,V1] ), aes(x = lead_time, y = skill, col = 'QR-NWP1'),alpha = 1, linetype = 1)+
    geom_line(data = data.table(lead_time = 1:80, skill = 1 - mod_int1_19$Results[lead_time>60& lead_time<=140, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Clima[lead_time>60& lead_time<=140, mean(pinball_loss(0.9, clima_pred90, PC1)), by = lead_time][,V1] ), aes(x = lead_time, y = skill, col = 'QR-Comb'),alpha = 1, linetype = 1)+

    # geom_line(data = data.table(lead_time = 1:80, skill = 1 - ERA_NWP_RQE1[date>=as.Date("2007-01-01") & lead_time>60& lead_time<=140, .(mean_test_loss = mean(mean_loss_1_17)), keyby = lead_time][,mean_test_loss]/ERA_NWP_raw_loss[lead_time>60& lead_time<=140, mean(raw_loss_09), by = lead_time][,V1] ), aes(x = lead_time, y = skill, col = 'RQE1'),alpha = 1)+
    # geom_line(data = data.table(lead_time = 1:80, skill = 1 - mod_17_1$Results[lead_time>60& lead_time<=140, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Interval_Mod_9_125_hs_1_2$Results[lead_time>60& lead_time<=140, mean(test_loss), by = lead_time][,V1] ), aes(x = lead_time, y = skill, col = 'QR-NWP1'),alpha = 1)+
    # 
    #     geom_line(data = data.table(lead_time = 1:80, skill = 1 - mod_int1_17$Results[lead_time>60& lead_time<=140, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Interval_Mod_9_125_1$Results[lead_time>60& lead_time<=140, mean(test_loss), by = lead_time][,V1] ), aes(x = lead_time, y = skill, col = 'QR-NWP Inter'),alpha = 1)+

    scale_x_continuous(breaks=seq(0, 20*4, by = 16),labels=seq(0, 20*4, by = 16)/4)+
    geom_hline(yintercept = 0, col = 'black',alpha = 0.6)+
    geom_hline(yintercept = 0.1, col = 'black',linetype = 'dashed', alpha = 0.6)+
    geom_hline(yintercept = -0.1, col = 'black',linetype = 'dashed', alpha = 0.6)+
    labs(color = "Model:", x = "Lead Time (Days after Re-weighting)", y = "Mean Skill Score",title = "Mean Skill Score for Re-weighted Models by Lead Time")+
scale_color_manual(values = c("RQE" = "red", "QR-NWP1" = "black","QR-Comb" = "blue"))+
    theme_bw()+
    theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), 
          legend.position = c(0.90, 0.62), legend.key.size = unit(0.53, "cm"), legend.box.background = element_rect(color = "black", fill = NA)) 
p
dev.off()
```

```{r}
# pdf("/Users/Eirik/Desktop/Master2023/ExportedPlots/Reweighting.pdf", height = 5, width = 7, pointsize = 12)
# plot(Mod_9_60_NWP1$Results[lead_time > 0 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time],
#      main = 'Reweighting', type = 'l', cex.main = 1.6, cex.lab = 1.3, ylim =c(2.5,12.5),xaxt = 'n', xlab = 'Horizon (days)', ylab = 'Pinball loss')
# lines(Mod_9_60_climatology$Results[, .(mean_test_loss = mean(clima_loss)), keyby = lead_time],col = 'blue')
# ax = pretty(1:120/4, 6)
# lines(mod_5$Results[lead_time>60, .(mean_test_loss = mean(test_loss)), keyby = lead_time],col = 'grey')
# lines(mod_10$Results[lead_time>60, .(mean_test_loss = mean(test_loss)), keyby = lead_time],col = 'grey')
# lines(mod_15$Results[lead_time>60, .(mean_test_loss = mean(test_loss)), keyby = lead_time],col = 'grey')
# lines(mod_18$Results[lead_time>60, .(mean_test_loss = mean(test_loss)), keyby = lead_time],col = 'grey')
# lines(mod_20$Results[lead_time>60, .(mean_test_loss = mean(test_loss)), keyby = lead_time],col = 'red')
# lines(mod_25$Results[lead_time>60, .(mean_test_loss = mean(test_loss)), keyby = lead_time],col = 'grey')
# axis(1, at = ax*4, labels = ax)
# abline(v = 60, lty = 2)
# legend("bottomright", lty = 1, cex=0.7, col = c('blue', 'black', 'grey','grey','grey', 'red','grey', 'grey'),
#        legend = c('Climatology', 'Best NWP model','K = 5','K = 10','K = 15', 'K = 18', 'K = 20','K = 25'), title = 'Model:')
# dev.off()
```

```{r}

# create ggplot object with first data table
p <- ggplot() +
    geom_line(data = mod_5_1$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 5'),alpha = 1)+
    geom_line(data = mod_10_1$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 10'),alpha = 1)+
    geom_line(data = mod_15_1$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 15'),alpha = 1)+

    geom_line(data = mod_20_1$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 20'),alpha = 1)+
    geom_line(data = mod_25_1$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 25'),alpha = 1)+
      geom_line(data= Mod_9_60_NWP1$Results[lead_time > 0 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'NWP'))+
geom_line(data = Mod_9_60_climatology$Results[lead_time > 0& lead_time<=120, .(mean_test_loss = mean(clima_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'Climatology'))+
        geom_line(data = mod_18_1$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 18'),alpha = 1)+
    ylim(2, 11.5)+
      theme(legend.position = c(0.90, 0.32)) +  
    scale_x_continuous(breaks=seq(0, 30, by = 5)*4,labels=c(0,5,10,15, 20,25,30))

p <- p + labs(color = "Model:", x = "Lead Time (Days)", y = "Pinball loss",title = "Pinball Loss for Re-weighted model")
p <- p + scale_color_manual(values = c("Climatology" = "blue", "NWP" = "black", 'K = 5' ="grey", 'K = 10' ="grey", 'K = 15' ="grey", 'K = 18' ="red", 'K = 20' ="grey", 'K = 25' ='grey'))
p


p <- ggplot() +
    geom_line(data = mod_5_2$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 5'),alpha = 1)+
    geom_line(data = mod_10_2$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 10'),alpha = 1)+
    geom_line(data = mod_15_2$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 15'),alpha = 1)+

    geom_line(data = mod_20_2$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 20'),alpha = 1)+
    geom_line(data = mod_25_2$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 25'),alpha = 1)+
      geom_line(data= Mod_9_60_NWP1$Results[lead_time > 0 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'NWP'))+
geom_line(data = Mod_9_60_climatology$Results[lead_time > 0& lead_time<=120, .(mean_test_loss = mean(clima_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'Climatology'))+
        geom_line(data = mod_18_2$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 18'),alpha = 1)+
    ylim(2, 11.5)+
      theme(legend.position = c(0.90, 0.32)) +  
    scale_x_continuous(breaks=seq(0, 30, by = 5)*4,labels=c(0,5,10,15, 20,25,30))

p <- p + labs(color = "Model:", x = "Lead Time (Days)", y = "Pinball loss",title = "Pinball Loss for Re-weighted model")
p <- p + scale_color_manual(values = c("Climatology" = "blue", "NWP" = "black", 'K = 5' ="grey", 'K = 10' ="grey", 'K = 15' ="grey", 'K = 18' ="red", 'K = 20' ="grey", 'K = 25' ='grey'))
p


p <- ggplot() +
    geom_line(data = mod_5_3$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 5'),alpha = 1)+
    geom_line(data = mod_10_3$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 10'),alpha = 1)+
    geom_line(data = mod_15_3$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 15'),alpha = 1)+

    geom_line(data = mod_20_3$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 20'),alpha = 1)+
    geom_line(data = mod_25_3$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 25'),alpha = 1)+
      geom_line(data= Mod_9_60_NWP1$Results[lead_time > 0 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'NWP'))+
geom_line(data = Mod_9_60_climatology$Results[lead_time > 0& lead_time<=120, .(mean_test_loss = mean(clima_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'Climatology'))+
        geom_line(data = mod_18_3$Results[lead_time>60 & lead_time<=120, .(mean_test_loss = mean(test_loss)), keyby = lead_time], aes(x = lead_time, y = mean_test_loss, col = 'K = 18'),alpha = 1)+
    ylim(2, 11.5)+
      theme(legend.position = c(0.90, 0.32)) +  
    scale_x_continuous(breaks=seq(0, 30, by = 5)*4,labels=c(0,5,10,15, 20,25,30))

p <- p + labs(color = "Model:", x = "Lead Time (Days)", y = "Pinball Loss",title = "Pinball Loss for Re-weighted model")
p <- p + scale_color_manual(values = c("Climatology" = "blue", "NWP" = "black", 'K = 5' ="grey", 'K = 10' ="grey", 'K = 15' ="grey", 'K = 18' ="red", 'K = 20' ="grey", 'K = 25' ='grey'))
p
```

```{r}
# for (i in 1:25){
#     assign(paste0("mod_",i, "_3"),get(paste0("mod_",i)))
# }

```

```{r}
pdf("/Users/Eirik/Desktop/Master2023/ExportedPlots/Skill_rew.pdf", height = 5, width = 7, pointsize = 12)

plot(1:40, 1 - mod_5$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/
         Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss] ,
     type = 'l',xaxt = 'n' , cex.main = 1.6, cex.lab = 1.3, col = 'grey', main = 'Skill Reweighting', ylab = 'Skill Score', xlab = 'Horizon (days) from re-weighting', ylim = c(-0.2, 0.6))
lines(1:40, 1 - mod_10$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/
          Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss] ,
      col = 'grey')
lines(1:40, 1 - mod_15$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/
          Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss] ,
      col = 'grey')
lines(1:40, 1 - mod_18$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/
          Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss] ,
      col = 'red')
lines(1:40, 1 - mod_20$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/
          Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss] ,
      col = 'grey')
lines(1:40, 1 - mod_25$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/
          Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss] ,
      col = 'grey')
ax = pretty(1:40, 5)
axis(1, at = ax, labels = ax/4)
abline(h = 0)
legend("topright", lty = 1, cex=0.7, col = c('grey', 'grey', 'grey', 'red', 'grey', 'grey'),
       legend = c('K = 5', 'K = 10','K = 15', 'K = 18', 'K = 20', 'K = 25'), title = 'Model:')
dev.off()
```


```{r}
p <- ggplot() +
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_5_1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 5'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_10_1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 10'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_15_1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 15'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_18_1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/ Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 18'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_20_1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 20'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_25_1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 25'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_18_1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_climatology$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(clima_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 18'),alpha = 1)+
      theme(legend.position = c(0.90, 0.72)) +
    scale_x_continuous(breaks=seq(0, 10, by = 2)*4,labels=c(0,2,4,6,8,10))+
 labs(color = "Model:", x = "Lead Time (Days)", y = "Skill Score",title = "Skill Score for Re-weighted model",
              subtitle = "-")+
    ylim(-0.2,0.65)+
 scale_color_manual(values = c('K = 5' ="grey", 'K = 10' ="grey", 'K = 15' ="grey", 'K = 18' ="red", 'K = 20' ="grey", 'K = 25' ='grey'))
p


p <- ggplot() +
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_5_2$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 5'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_10_2$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 10'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_15_2$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 15'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_18_2$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/ Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 18'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_20_2$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 20'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_25_2$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 25'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_18_2$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_climatology$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(clima_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 18'),alpha = 1)+
      theme(legend.position = c(0.90, 0.72)) +
    scale_x_continuous(breaks=seq(0, 10, by = 2)*4,labels=c(0,2,4,6,8,10))+
 labs(color = "Model:", x = "Lead Time (Days)", y = "Skill Score",title = "Skill Score for Re-weighted model",
              subtitle = "-")+
    ylim(-0.2,0.65)+
 scale_color_manual(values = c('K = 5' ="grey", 'K = 10' ="grey", 'K = 15' ="grey", 'K = 18' ="red", 'K = 20' ="grey", 'K = 25' ='grey'))
p


p <- ggplot() +
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_5_3$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 5'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_10_3$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 10'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_15_3$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 15'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_18_3$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/ Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 18'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_20_3$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 20'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_25_3$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_NWP1$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 25'),alpha = 1)+
    geom_line(data = data.table(x = 1:40,mean_test_loss = 1 -mod_18_3$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(test_loss)), keyby = lead_time][,mean_test_loss]/Mod_9_60_climatology$Results[lead_time>60& lead_time<=100, .(mean_test_loss = mean(clima_loss)), keyby = lead_time][,mean_test_loss]), aes(x = x, y = mean_test_loss, col = 'K = 18'),alpha = 1)+
      theme(legend.position = c(0.90, 0.72)) +
    scale_x_continuous(breaks=seq(0, 10, by = 2)*4,labels=c(0,2,4,6,8,10))+
 labs(color = "Model:", x = "Lead Time (Days)", y = "Skill Score",title = "Skill Score for Re-weighted model",
              subtitle = "-")+
    ylim(-0.2,0.65)+
 scale_color_manual(values = c('K = 5' ="grey", 'K = 10' ="grey", 'K = 15' ="grey", 'K = 18' ="red", 'K = 20' ="grey", 'K = 25' ='grey'))
p
```


```{r}
ERA_NWP_raw_loss[lead_time>60&lead_time<=80,mean(raw_loss_09)]


l_5 = rep(NA,25)
l_7 = rep(NA,25)
l_10 = rep(NA,25)
l_15 = rep(NA,25)
for (k in 1:25){
    mod_name = paste0('mod_',k, "_1")
    mod = get(mod_name)
    l_5[k] = mod$Results[lead_time>60&lead_time<=80, mean(test_loss)]
    l_7[k] = mod$Results[lead_time>60&lead_time<=88, mean(test_loss)]
    l_10[k] = mod$Results[lead_time>60&lead_time<=100, mean(test_loss)]
    l_15[k] = mod$Results[lead_time>60&lead_time<=120, mean(test_loss)]
}
K_1_plot = data.table(l_5 = l_5, l_7 = l_7,l_10 = l_10,l_15 = l_15, x = 1:25)
K_1_plot = rbind(
    data.table(l_5 = ERA_NWP_raw_loss[lead_time>60&lead_time<=80,mean(raw_loss_09)], 
                l_7 = ERA_NWP_raw_loss[lead_time>60&lead_time<=88,mean(raw_loss_09)], 
               l_10 = ERA_NWP_raw_loss[lead_time>60&lead_time<=100,mean(raw_loss_09)],
               l_15 = ERA_NWP_raw_loss[lead_time>60&lead_time<=120,mean(raw_loss_09)], x =0
                 ),
    K_1_plot)

l_5 = rep(NA,25)
l_7 = rep(NA,25)
l_10 = rep(NA,25)
l_15 = rep(NA,25)
for (k in 1:25){
    mod_name = paste0('mod_',k, "_2")
    mod = get(mod_name)
    l_5[k] = mod$Results[lead_time>60&lead_time<=80, mean(test_loss)]
    l_7[k] = mod$Results[lead_time>60&lead_time<=88, mean(test_loss)]
    l_10[k] = mod$Results[lead_time>60&lead_time<=100, mean(test_loss)]
    l_15[k] = mod$Results[lead_time>60&lead_time<=120, mean(test_loss)]
}
K_2_plot = data.table(l_5 = l_5, l_7 = l_7,l_10 = l_10,l_15 = l_15, x = 1:25)

l_5 = rep(NA,25)
l_7 = rep(NA,25)
l_10 = rep(NA,25)
l_15 = rep(NA,25)
for (k in 1:25){
    mod_name = paste0('mod_',k, "_3")
    mod = get(mod_name)
    l_5[k] = mod$Results[lead_time>60&lead_time<=80, mean(test_loss)]
    l_7[k] = mod$Results[lead_time>60&lead_time<=88, mean(test_loss)]
    l_10[k] = mod$Results[lead_time>60&lead_time<=100, mean(test_loss)]
    l_15[k] = mod$Results[lead_time>60&lead_time<=120, mean(test_loss)]
}
K_3_plot = data.table(l_5 = l_5, l_7 = l_7,l_10 = l_10,l_15 = l_15, x = 1:25)
```

```{r}
l_5 = rep(NA,25)
l_7 = rep(NA,25)
l_10 = rep(NA,25)
l_15 = rep(NA,25)
for (k in 1:25){
    mod_name = paste0('mod_int1_',k)
    mod = get(mod_name)
    l_5[k] = mod$Results[lead_time>60&lead_time<=80, mean(test_loss)]
    l_7[k] = mod$Results[lead_time>60&lead_time<=88, mean(test_loss)]
    l_10[k] = mod$Results[lead_time>60&lead_time<=100, mean(test_loss)]
    l_15[k] = mod$Results[lead_time>60&lead_time<=120, mean(test_loss)]
}
K_int_1_plot = data.table(l_5 = l_5, l_7 = l_7,l_10 = l_10,l_15 = l_15, x = 1:25)

l_5 = rep(NA,25)
l_7 = rep(NA,25)
l_10 = rep(NA,25)
l_15 = rep(NA,25)
for (k in 1:25){
    mod_name = paste0('mod_int2_',k)
    mod = get(mod_name)
    l_5[k] = mod$Results[lead_time>60&lead_time<=80, mean(test_loss)]
    l_7[k] = mod$Results[lead_time>60&lead_time<=88, mean(test_loss)]
    l_10[k] = mod$Results[lead_time>60&lead_time<=100, mean(test_loss)]
    l_15[k] = mod$Results[lead_time>60&lead_time<=120, mean(test_loss)]
}
K_int_2_plot = data.table(l_5 = l_5, l_7 = l_7,l_10 = l_10,l_15 = l_15, x = 1:25)

l_5 = rep(NA,25)
l_7 = rep(NA,25)
l_10 = rep(NA,25)
l_15 = rep(NA,25)
for (k in 1:25){
    mod_name = paste0('mod_int3_',k)
    mod = get(mod_name)
    l_5[k] = mod$Results[lead_time>60&lead_time<=80, mean(test_loss)]
    l_7[k] = mod$Results[lead_time>60&lead_time<=88, mean(test_loss)]
    l_10[k] = mod$Results[lead_time>60&lead_time<=100, mean(test_loss)]
    l_15[k] = mod$Results[lead_time>60&lead_time<=120, mean(test_loss)]
}
K_int_3_plot = data.table(l_5 = l_5, l_7 = l_7,l_10 = l_10,l_15 = l_15, x = 1:25)
```

```{r}
pdf("/Users/Eirik/Desktop/Master2023/ExportedPlots/Loss_period.pdf", height = 5, width = 7, pointsize = 12)

plot(l_5, ylim = c(6.4, 9.2), main = 'Pinball loss comparing K for different loss periods',
     xlab = 'K - tuning parameter', cex.main = 1.6,  cex.lab = 1.3, ylab = 'Pinball Loss', xaxt = 'n')
points(l_7, col = 'purple')
points(l_10, col = 'red')
points(l_15, col = 'blue')
points(which.min(l_5), min(l_5), col = 'black', pch = 16)
points(which.min(l_7), min(l_7), col = 'purple', pch = 16)
points(which.min(l_10), min(l_10), col = 'red', pch = 16)
points(which.min(l_15), min(l_15), col = 'blue', pch = 16)

legend("bottomleft", lty = 1, cex=0.7, col = c('black', 'purple', 'red', 'blue'),
       legend = c('5 days', '7 days', '10 days', '15 days'), title = 'Loss period:')
ax = c(1,5,10,15,20,25)
sq = exp(seq(log(0.000001), log(0.01), length.out = 25))
axis(1, at = ax, labels = format(sq[ax], scientific = TRUE, digits = 3))
dev.off()
```


```{r}
pdf("/Users/Eirik/Desktop/Master2023/ExportedPlots/Loss_period.pdf", height = 7, width = 9, pointsize = 12)
p <- ggplot() +
    geom_point(data = K_1_plot,aes(x = x, y = l_5, col = 'Days 1:5'),size = 2.5, shape = 21)+
    geom_point(data = K_1_plot,aes(x = x, y = l_7, col = 'Days 1:7'),size = 2.5, shape = 21)+
    geom_point(data = K_1_plot,aes(x = x, y = l_10, col = 'Days 1:10'),size = 2.5, shape = 21)+
    geom_point(data = K_1_plot,aes(x = x, y = l_15, col = 'Days 1:15'),size = 2.5, shape = 21)+
    geom_point(data = K_1_plot,aes(x = x[which.min(l_5)], y = l_5[which.min(l_5)], col = 'Days 1:5'),size = 2.6, shape = 19)+
    geom_point(data = K_1_plot,aes(x = x[which.min(l_7)], y = l_7[which.min(l_7)], col = 'Days 1:7'),size = 2.6, shape = 19)+
    geom_point(data = K_1_plot,aes(x = x[which.min(l_10)], y = l_10[which.min(l_10)], col = 'Days 1:10'),size = 2.6, shape = 19)+
    geom_point(data = K_1_plot,aes(x = x[which.min(l_15)], y = l_15[which.min(l_15)], col = 'Days 1:15'),size = 2.6, shape = 19)+
      theme(legend.position = c(0.15, 0.20), legend.key.size = unit(0.42, "cm"),  
            legend.key = element_rect(fill = "transparent"),
            legend.box.background = element_rect(color = "black", size = 0.75),
            panel.border = element_rect(colour = "black", fill = NA, size = 1),
            panel.background = element_rect(fill = "white", color = "black"),
        plot.margin = unit(c(1, 1, 1, 1), "cm")
          )   +
scale_x_continuous(breaks=c(0, 5,10,15,20,25),labels=function(x) c(0, sprintf("%0.2e", exp(seq(log(0.000001), log(0.01), length.out = 25))))[c(1, 6,11,16,21,26)])+
 labs(color = "Loss Period:", x = expression(paste(gamma, " - Tuning Parameter")), y = "Pinball Loss",title = expression(paste("Mean Pinball Loss by Tuning Parameter ",gamma," for Different Loss Periods")))+
   ylim(5,9.5)+
 scale_color_manual(values = c('Days 1:5' ="purple", 'Days 1:7' ="orange", 'Days 1:10' ="green", 'Days 1:15' ="red"))
p
dev.off()
p <- ggplot() +
    geom_point(data = K_2_plot,aes(x = x, y = l_5, col = '5 Days'),size = 1.6, shape = 21)+
    geom_point(data = K_2_plot,aes(x = x, y = l_7, col = '7 Days'),size = 1.6, shape = 21)+
    geom_point(data = K_2_plot,aes(x = x, y = l_10, col = '10 Days'),size = 1.6, shape = 21)+
    geom_point(data = K_2_plot,aes(x = x, y = l_15, col = '15 Days'),size = 1.6, shape = 21)+
    geom_point(data = K_2_plot,aes(x = x[which.min(l_5)], y = l_5[which.min(l_5)], col = '5 Days'),size = 1.6, shape = 19)+
    geom_point(data = K_2_plot,aes(x = x[which.min(l_7)], y = l_7[which.min(l_7)], col = '7 Days'),size = 1.6, shape = 19)+
    geom_point(data = K_2_plot,aes(x = x[which.min(l_10)], y = l_10[which.min(l_10)], col = '10 Days'),size = 1.6, shape = 19)+
    geom_point(data = K_2_plot,aes(x = x[which.min(l_15)], y = l_15[which.min(l_15)], col = '15 Days'),size = 1.6, shape = 19)+
      theme(legend.position = c(0.10, 0.42)) +
 scale_x_continuous(breaks=c(1, 5,10,15,20,25),labels=function(x) sprintf("%0.2e", exp(seq(log(0.000001), log(0.01), length.out = 25)))[c(1, 5,10,15,20,25)])+
 labs(color = "Loss Period:", x = "K - Tuning Parameter", y = "Pinball Loss",title = "Pinball Loss comparing K for different Loss Periods",
              subtitle = "-")+
   ylim(6,9.5)+
 scale_color_manual(values = c('5 Days' ="purple", '7 Days' ="orange", '10 Days' ="green", '15 Days' ="red"))
p
p <- ggplot() +
    geom_point(data = K_3_plot,aes(x = x, y = l_5, col = '5 Days'),size = 1.5, shape = 21)+
    geom_point(data = K_3_plot,aes(x = x, y = l_7, col = '7 Days'),size = 1.5, shape = 21)+
    geom_point(data = K_3_plot,aes(x = x, y = l_10, col = '10 Days'),size = 1.5, shape = 21)+
    geom_point(data = K_3_plot,aes(x = x, y = l_15, col = '15 Days'),size = 1.5, shape = 21)+
    geom_point(data = K_3_plot,aes(x = x[which.min(l_5)], y = l_5[which.min(l_5)], col = '5 Days'),size = 1.5, shape = 19)+
    geom_point(data = K_3_plot,aes(x = x[which.min(l_7)], y = l_7[which.min(l_7)], col = '7 Days'),size = 1.5, shape = 19)+
    geom_point(data = K_3_plot,aes(x = x[which.min(l_10)], y = l_10[which.min(l_10)], col = '10 Days'),size = 1.5, shape = 19)+
    geom_point(data = K_3_plot,aes(x = x[which.min(l_15)], y = l_15[which.min(l_15)], col = '15 Days'),size = 1.5, shape = 19)+
      theme(legend.position = c(0.10, 0.32)) +
    scale_x_continuous(breaks=c(1, 5,10,15,20,25),labels=function(x) sprintf("%0.2e", exp(seq(log(0.000001), log(0.01), length.out = 25)))[c(1, 5,10,15,20,25)])+
 labs(color = "Loss Period:", x = expression(paste(gamma, " - Tuning Parameter")), y = "Pinball Loss",title = expression(paste("Pinball Loss by tuning parameter ",gamma," for different Loss Periods")),
              subtitle = "-")+
   ylim(6,9.5)+
 scale_color_manual(values = c('5 Days' ="purple", '7 Days' ="orange", '10 Days' ="green", '15 Days' ="red"))
p
```



```{r}
Size_plot = Aggregate_adj_size_plot[,.(`5`, `10`, `15`, `18`, `20`, `25`, `2days_17`, `3days_17`)]
Size_plot$x = 1:64
pdf("/Users/Eirik/Desktop/Master2023/ExportedPlots/Weight_adj.pdf", height = 7, width = 9, pointsize = 12)
p <- ggplot() +
    geom_line(data = Size_plot,aes(x = x, y = `5` , color = 'Day5'))+
    geom_line(data = Size_plot,aes(x = x, y = `10`, color = 'Day10'))+
    geom_line(data = Size_plot,aes(x = x, y = `15`, color = 'Day15'))+
    geom_line(data = Size_plot,aes(x = x, y = `18`, color = 'Day18'))+
    geom_line(data = Size_plot,aes(x = x, y = `20`, color = 'Day20'))+
    geom_line(data = Size_plot,aes(x = x, y = `25`, color = 'Day25'))+
    geom_line(data = Size_plot,aes(x = x, y = `2days_17`, color = 'Days_2'))+
    geom_line(data = Size_plot,aes(x = x, y = `3days_17`, color = 'Days_3'))+
      theme(legend.position = c(0.85, 0.80), legend.key.size = unit(0.42, "cm"),  
            legend.key = element_rect(fill = "transparent"),
            legend.box.background = element_rect(color = "black", size = 0.75),
            panel.border = element_rect(colour = "black", fill = NA, size = 1),
            panel.background = element_rect(fill = "white", color = "black"),
        plot.margin = unit(c(1, 1, 1, 1), "cm")
          ) +
 scale_x_continuous(breaks = seq(1, 64, by = 4),
                     labels = c("","", "", "", "5", "", "", "","", "10", "", "", "","", "15","")) +
 labs(color = "Adjustment Set-up:", x = "Lead Time (Days after Re-initialization)", y = "Factor Loading Absolute Adjustment",title = "Mean Absolute Weight Adjustment by Lead Time")+
   ylim(0,27)+
 scale_color_manual(values = c('Day5'="#FFCDD2",'Day10'="#EF9A9A", 'Day15'="#E57373",'Day18'="#EF5350", 'Day20'="#F44336", 'Day25'='#D32F2F','Days_2'="blue", 'Days_3'="black"),
                    labels = c(Day5 = expression(paste("1 Day (",gamma, "=4.6e-06)")),
                               Day10 = expression(paste("1 Day (",gamma, "=3.2e-05)")),
                               Day15 = expression(paste("1 Day (",gamma, "=2.2e-04)")),
                               Day18 = expression(paste("1 Day (",gamma, "=4.6e-04)")),
                               Day20 = expression(paste("1 Day (",gamma, "=1.5e-03)")),
                               Day25 = expression(paste("1 Day (",gamma, "=0.01)")),
                               Days_2 = expression(paste("2 Days (",gamma, "4.6e-04)")),
                               Days_3 = expression(paste("3 Days (",gamma, "4.6e-04)"))
                               )
                    )
p
dev.off()
```



```{r}
#m = 1
#y = 2008
#m = 12
#y = 2008
m = 12
y = 2013
Pred_plot = data.table(WQE = ERA_NWP_raw_loss[month(date)==m & year(date) == y &lead_time <121,NWP_PC1_q90],
                       PC1 = mod_17$Results[month==m & year(date) == y &lead_time <121, PC1],
                       RQE_17 = mod_17$Results[month==m & year(date) == y &lead_time <121, NWP1_re90],
                       Clima = Mod_9_60_climatology$Results[month(date)==m  & year(date) == y &lead_time <121, clima_pred],
                       x = 1:120
)

ERA_NWP_raw_loss[mday(date) >15 &month(date)==m & year(date) == y &lead_time <121,mean(raw_loss_09)] #7.2258

mod_17$Results[mday(date) >15 &month(date)==m & year(date) == y &lead_time <121,mean(test_loss)] #


dates = format(rep(seq(as.Date("2013-12-01"), as.Date("2013-12-30"), by = "day"), each = 4), "%d-%m")

#pdf("/Users/Eirik/Desktop/Master2023/ExportedPlots/Pred_rew.pdf", height = 7, width = 9, pointsize = 12)
p = ggplot() +
    geom_line(data = Pred_plot,aes(x = x, y = WQE, col = 'NWP-WQE'))+
    geom_point(data = Pred_plot,aes(x = x, y = PC1, col = 'Observed'))+
    geom_line(data = Pred_plot[61:120],aes(x = x, y = RQE_17, col = 'NWP-RQE'))+
    geom_line(data = Pred_plot[1:120],aes(x = x, y = Clima, col = 'Climatology'))+
    
    theme(legend.position = c(0.9, 0.4), legend.key.size = unit(0.53, "cm"),  
          legend.key = element_rect(fill = "transparent"),
          legend.box.background = element_rect(color = "black", size = 0.75),
          panel.border = element_rect(colour = "black", fill = NA, size = 1),
          panel.background = element_rect(fill = "white", color = "black"),
          plot.margin = unit(c(1, 1, 1, 1), "cm")
    )  +
    scale_x_continuous(breaks = seq(0, 120, 20), labels = dates[c(1, 20, 40, 60, 80, 100, 120)])+
    
    #scale_x_continuous(breaks = seq(0,60, 10), labels = c(0, 5, 10, 15))+
    labs(color = "Model:", x = "Date (2013)", y = "Factor Loading Value",title = "Predictive Adjustment (December 2013)")+
    #ylim(-150,250)
    scale_color_manual(values = c('Observed' = 'black', 'NWP-WQE' = 'blue', 'NWP-RQE' = 'red', 'Climatology' = 'grey'))
p
dev.off()


```

